# config java proxy
#- name: update repo
#  apt: update_cache=yes
#  become: yes
- name: install haproxy and socat
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - haproxy
    - socat
- name: enable haproxy
  lineinfile: path=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  become: yes
- name: copy conf file
  template: src={{ haproxy_file }} dest=/etc/haproxy/haproxy.cfg validate="haproxy -c -f %s" owner=root group=root
  become: yes
  notify:
    - reload haproxy
- name: start haproxy
  service: name=haproxy state=started enabled=yes
  become: yes
