- name: pull {{ project }} from gitlab
  git:
    repo: git@{{ git_url }}:{{ group }}/{{ project }}.git
    dest: files/{{ env }}/{{ project }}
    version: "{{ branch }}"
  delegate_to: localhost
  run_once: true
  register: change
- name: package {{ project }}
  shell: chdir=files/{{ env }}/{{ project }} mvn clean package -Dmaven.test.skip=true
  delegate_to: localhost
  run_once: true
  when: change|changed
- name: mkdir {{ project }}
  file: path=/home/{{ ansible_ssh_user }}/{{ project }} state=directory
  when: change|changed
- name: push supervisor configuration
  template: src=java_template.conf dest=/etc/supervisor/conf.d/{{ project }}.conf
  become: yes
  notify:
   - restart supervisor
  when: change|changed
- name: backup old file
  shell: chdir=/home/{{ ansible_ssh_user }} rsync -az --delete {{ project }}/ {{ project }}.bak/
  when: change|changed
- name: push {{ project }} package
  copy: src=files/{{ env }}/{{ project }}/target/{{ jar_code }} dest=/home/{{ ansible_ssh_user }}/{{ project }}
  when: change|changed and '{{ project }}' == 'framework-gateway-server'
- name: push {{ project }} package
  copy: src=files/{{ env }}/{{ project }}/target/{{ jar_code }} dest=/home/{{ ansible_ssh_user }}/{{ project }}
  notify:
   - restart {{ project }}
  when: change|changed and '{{ project }}' != 'framework-gateway-server'
- name: give up all changes
  shell: chdir=files/{{ env }}/{{ project }} git checkout . && git clean -xdf
  delegate_to: localhost
  run_once: true
  when: change|changed
