- name: install supervisor
  apt: name=supervisor state=present
  become: yes
- name: start supervisor
  service: name=supervisor state=started enabled=yes
  become: yes
- name: config sudo PATH
  lineinfile: dest=~/.bashrc line="alias sudo='sudo env PATH=$PATH'"

# config java
- name: download jdk file
  get_url: url=http://172.17.20.13/jdk-8u121-linux-x64.tar.gz dest=/usr/local/
  become: yes
- name: untar jdk file
  unarchive: src=/usr/local/jdk-8u121-linux-x64.tar.gz dest=/usr/local/ remote_src=yes
  become: yes
- name: add JAVA_HOME and java PATH
  lineinfile: path=/etc/profile line="export JAVA_HOME=/usr/local/jdk1.8.0_121"
  become: yes
- name: add java PATH
  lineinfile: path=/etc/profile line="export PATH=$JAVA_HOME/bin:$PATH"
  become: yes

# config mvn
- name: download mvn file
  get_url: url=http://172.17.20.13/apache-maven-3.5.0-bin.zip dest=/usr/local/
  become: yes
- name: untar mvn file
  unarchive: src=/usr/local/apache-maven-3.5.0-bin.zip dest=/usr/local/ remote_src=yes
  become: yes
- name: add MAVEN_HOME
  lineinfile: path=/etc/profile line="export MAVEN_HOME=/usr/local/apache-maven-3.5.0"
  become: yes
- name: add mvn PATH
  lineinfile: path=/etc/profile line="export PATH=$PATH:${MAVEN_HOME}/bin"
  become: yes

