- name: install some package
  apt: name={{ item }} state=present
  with_items:
    - zlib1g-dev  
    - libpcre3 
    - libpcre3-dev 
    - openssl 
    - libssl-dev
  become: yes
- name: download nginx file
  get_url: url=http://172.17.20.13/nginx-1.12.0.tar.gz dest=/usr/local/
  become: yes
- name: untar nginx file
  unarchive: src=/usr/local/nginx-1.12.0.tar.gz dest=/usr/local remote_src=yes
  become: yes

- name: mkdir
  file: path=/home/{{ ansible_ssh_user }}/nginx state=directory
- name: config and make
  shell: chdir=/usr/local/nginx-1.12.0 ./configure --prefix=/home/{{ ansible_ssh_user}}/nginx --with-http_ssl_module && make creates=/home/{{ ansible_ssh_user }}/nginx/sbin/nginx
  register: nginx
  become: yes 
- name: make install
  shell: chdir=/usr/local/nginx-1.12.0 make install 
  when: nginx|changed

- name: copy nginx conf
  template: src={{ item }} dest=/home/{{ ansible_ssh_user }}/nginx/conf
  with_items:
    - nginx.conf
    - gzip.conf
    - ssl.conf
- name: copy site
  copy: src="{{ site }}" dest=/home/{{ ansible_ssh_user }}/nginx/conf
- name: copy keyfile
  copy: src=keyfile/cert dest=/home/{{ ansible_ssh_user }}/nginx

