- name: start {{ project }} service
  shell: supervisorctl start '{{ project }}'
  become: yes
- name: wait {{ project }} port up
  wait_for: host='{{ inventory_hostname }}' port='{{ project_port }}' state=started delay='{{ start_sec }}'
- name: enable {{ project }} in haproxy
  haproxy: state=enabled backend='{{ project }}' host='{{ inventory_hostname }}' socket=/var/run/haproxy.sock wait=yes
  delegate_to: '{{ haproxy }}'
  become: yes
- name: delete bad dir
  shell: find /tmp/* -maxdepth 0 -type d -name "*.{{ project_port }}" -mtime +1|xargs -i rm -rf {}
  become: yes

